Producer.create(name:"Ziemann, Corkery and Breitenberg",address:"Maple",address2:"Cambará",county_id:15,contact_phone:"303-57-1634",contact_email:"mauten0@nbcnews.com",password:"fLaT75MXi")
Producer.create(name:"Sauer Inc",address:"Rusk",address2:"Kruisfontein",county_id:13,contact_phone:"584-54-0779",contact_email:"hthurlborn1@businessweek.com",password:"J1VN45KxrU0")
Producer.create(name:"Ziemann LLC",address:"Ryan",address2:"Shcherbinka",county_id:17,contact_phone:"877-67-7479",contact_email:"ihasard2@discovery.com",password:"HAsxCOXI")
Producer.create(name:"Hettinger LLC",address:"Westend",address2:"Petrovo-Dal’neye",county_id:19,contact_phone:"317-36-0474",contact_email:"fcatteroll3@admin.ch",password:"D4BCT0ndJB")
Producer.create(name:"Fisher, Muller and Sawayn",address:"Springs",address2:"Utabi",county_id:6,contact_phone:"265-36-2183",contact_email:"jbain4@vkontakte.ru",password:"cq0ulZ")
Producer.create(name:"Bahringer-Schoen",address:"Lillian",address2:"Aţ Ţafīlah",county_id:17,contact_phone:"570-75-8711",contact_email:"kcolquete5@discovery.com",password:"klUKuzvB")
Producer.create(name:"Ondricka-Nolan",address:"Glacier Hill",address2:"Gulong",county_id:30,contact_phone:"825-27-3137",contact_email:"evalentim6@bigcartel.com",password:"H4809aQBfg")
Producer.create(name:"Hilpert-McKenzie",address:"Forest Run",address2:"Libei",county_id:6,contact_phone:"880-93-8045",contact_email:"dhinchcliffe7@examiner.com",password:"ke23Nx")
Producer.create(name:"Effertz and Sons",address:"Ronald Regan",address2:"Molugan",county_id:15,contact_phone:"183-04-4359",contact_email:"cbrahm8@ovh.net",password:"SZfkYtnobEV")
Producer.create(name:"Stehr-Bartoletti",address:"Dottie",address2:"Gaojingzhuang",county_id:5,contact_phone:"833-72-0564",contact_email:"fcaccavari9@liveinternet.ru",password:"EqXZoWOgUTw")
Producer.create(name:"Hand Group",address:"Hallows",address2:"Lajedo",county_id:24,contact_phone:"304-22-0553",contact_email:"xruslingea@stumbleupon.com",password:"AipgyzG")
Producer.create(name:"Lehner, D'Amore and McDermott",address:"Village Green",address2:"Berlin",county_id:20,contact_phone:"165-19-9366",contact_email:"mcutmereb@cpanel.net",password:"Jk9P8YM7iUl")
Producer.create(name:"Dicki, Bayer and Zemlak",address:"Corry",address2:"Zakhim",county_id:28,contact_phone:"833-43-0065",contact_email:"ffominovc@studiopress.com",password:"uByMHU6k")
Producer.create(name:"Effertz-Becker",address:"Onsgard",address2:"Huatan",county_id:26,contact_phone:"599-06-2059",contact_email:"sbalaamd@lulu.com",password:"ZiYAtG")
Producer.create(name:"Gorczany, Cummerata and Grant",address:"Thierer",address2:"Murcki",county_id:7,contact_phone:"242-20-2047",contact_email:"lbellangere@skype.com",password:"NAVFWFt")
Producer.create(name:"Funk Inc",address:"Sage",address2:"Shengli",county_id:16,contact_phone:"510-89-0926",contact_email:"icrundenf@weather.com",password:"EzN8zhH")
Producer.create(name:"Mayer LLC",address:"Lindbergh",address2:"Abbottābād",county_id:13,contact_phone:"577-28-8058",contact_email:"hcheesemang@com.com",password:"Atc8Nn0")
Producer.create(name:"Flatley-Gaylord",address:"Chinook",address2:"Lyubymivka",county_id:16,contact_phone:"377-45-5604",contact_email:"kvakhoninh@acquirethisname.com",password:"rYtjhUGnHF")
Producer.create(name:"VonRueden-Dibbert",address:"Bay",address2:"Tabogon",county_id:20,contact_phone:"620-57-7683",contact_email:"lkiehnlti@yandex.ru",password:"XMFTfZLLZRH")
Producer.create(name:"Krajcik-Ortiz",address:"Claremont",address2:"Ebene",county_id:6,contact_phone:"657-23-7296",contact_email:"nauklandj@drupal.org",password:"4wnEXm96")
Producer.create(name:"Hahn-Bednar",address:"Kim",address2:"Jiangtun",county_id:14,contact_phone:"548-07-0880",contact_email:"eraouxk@cbc.ca",password:"NutCMjV4En")
Producer.create(name:"Leannon, Stroman and Barton",address:"Holy Cross",address2:"Newark",county_id:14,contact_phone:"115-18-9511",contact_email:"cjoannetl@1688.com",password:"IjtIGNp")
Producer.create(name:"Morar, Marks and Wisoky",address:"Northport",address2:"Ibrā’",county_id:13,contact_phone:"872-26-8820",contact_email:"hcalderam@rediff.com",password:"Q1yp6q")
Producer.create(name:"Ritchie, Kerluke and Steuber",address:"Lindbergh",address2:"Radenković",county_id:18,contact_phone:"237-30-8551",contact_email:"pmaudlenn@squarespace.com",password:"8qS93B")
Producer.create(name:"Altenwerth, Hane and McClure",address:"Erie",address2:"Kedungwungu",county_id:22,contact_phone:"170-04-9565",contact_email:"jmcconachieo@fastcompany.com",password:"4jTC4AJ")
Producer.create(name:"Koelpin-Lang",address:"Mifflin",address2:"Mutsu",county_id:26,contact_phone:"312-80-5465",contact_email:"tcosinsp@amazon.de",password:"0mrSkiG")
Producer.create(name:"Prohaska, Lebsack and Beatty",address:"Northfield",address2:"Heby",county_id:25,contact_phone:"335-45-3471",contact_email:"yriddettq@simplemachines.org",password:"tEhQQUho")
Producer.create(name:"Bergnaum, Spencer and Rau",address:"Macpherson",address2:"Dondon",county_id:15,contact_phone:"362-59-1111",contact_email:"cfrostickr@cbslocal.com",password:"JathDtnmZ")
Producer.create(name:"Gerhold-Nolan",address:"Kingsford",address2:"Soio",county_id:5,contact_phone:"599-82-9490",contact_email:"emorrisseys@oakley.com",password:"J7dW8T5")
Producer.create(name:"Batz LLC",address:"Linden",address2:"Murun-kuren",county_id:8,contact_phone:"135-17-6192",contact_email:"fcheeverst@simplemachines.org",password:"uYV6daYlXh")
Producer.create(name:"Upton Group",address:"Daystar",address2:"Santa Rita",county_id:5,contact_phone:"457-74-1205",contact_email:"amatthiusu@weibo.com",password:"OgEcZw7")
Producer.create(name:"Bernier LLC",address:"Westend",address2:"Montes",county_id:15,contact_phone:"847-62-9182",contact_email:"cmactrustramv@bbc.co.uk",password:"TwwKm5Epn2fR")
Producer.create(name:"Mann-Kassulke",address:"Eagle Crest",address2:"Shuitou",county_id:30,contact_phone:"310-95-4557",contact_email:"mmarriottw@adobe.com",password:"cxOdk44TkTkG")
Producer.create(name:"Funk Inc",address:"Jana",address2:"Jing’an",county_id:15,contact_phone:"312-53-3827",contact_email:"sbirckmannx@ted.com",password:"D4t94P")
Producer.create(name:"Fisher, Rolfson and Lowe",address:"Stang",address2:"Bunirasa",county_id:26,contact_phone:"116-37-5469",contact_email:"gcalowy@twitter.com",password:"ckbtPlv1q4")
Producer.create(name:"Ryan Group",address:"4th",address2:"Asikkala",county_id:6,contact_phone:"697-04-1287",contact_email:"hcrippinz@yellowbook.com",password:"LczNlyN")
Producer.create(name:"Sporer-Legros",address:"Manufacturers",address2:"Vorzel’",county_id:5,contact_phone:"563-57-8025",contact_email:"leagling10@usda.gov",password:"djqEuhVAjN")
Producer.create(name:"Macejkovic-Yost",address:"4th",address2:"Ban Ko Lan",county_id:26,contact_phone:"566-83-3924",contact_email:"epevsner11@techcrunch.com",password:"E03eGo1n5")
Producer.create(name:"Bernhard-Gerlach",address:"3rd",address2:"Kaolinovo",county_id:27,contact_phone:"151-77-7068",contact_email:"gsummerley12@digg.com",password:"977EjBhNrTFk")
Producer.create(name:"Wintheiser Inc",address:"Hauk",address2:"Hallstahammar",county_id:32,contact_phone:"427-72-1316",contact_email:"tlacelett13@noaa.gov",password:"WE8Eb7Z")
Producer.create(name:"Bruen-Kemmer",address:"Banding",address2:"Yang Chum Noi",county_id:13,contact_phone:"478-35-0693",contact_email:"adrohun14@harvard.edu",password:"W34xben5w")
Producer.create(name:"Homenick, Bayer and Lynch",address:"Iowa",address2:"Salon-de-Provence",county_id:5,contact_phone:"135-75-8196",contact_email:"alyal15@xing.com",password:"L0KTKnbP")
Producer.create(name:"Kovacek and Sons",address:"Acker",address2:"Žirovnice",county_id:3,contact_phone:"898-52-4491",contact_email:"lmathis16@ca.gov",password:"SuDgh1syu")
Producer.create(name:"Goldner, Olson and Corkery",address:"Dwight",address2:"Brasília de Minas",county_id:21,contact_phone:"340-46-9148",contact_email:"ebeachamp17@ebay.co.uk",password:"SQITB1wB0Z")
Producer.create(name:"Gutkowski, Beier and Kreiger",address:"Bonner",address2:"Nizhnyaya Tura",county_id:14,contact_phone:"104-30-5799",contact_email:"wbicksteth18@google.cn",password:"HVPQSxAFt3n")
Producer.create(name:"Haley Inc",address:"Northwestern",address2:"Sagrada Familia",county_id:1,contact_phone:"672-11-1820",contact_email:"jbausor19@hc360.com",password:"TGiDV9tmGQL")
Producer.create(name:"Baumbach, Weimann and Hettinger",address:"Bluestem",address2:"Jönköping",county_id:9,contact_phone:"591-61-1686",contact_email:"mboarleyson1a@dell.com",password:"gdnbJN9jK")
Producer.create(name:"Huel, Labadie and Cummings",address:"David",address2:"Argostólion",county_id:16,contact_phone:"170-29-0474",contact_email:"ehryncewicz1b@cmu.edu",password:"tcbnM2")
Producer.create(name:"Farrell Inc",address:"5th",address2:"5 de Mayo",county_id:23,contact_phone:"242-22-2172",contact_email:"rshyres1c@bbb.org",password:"dvMBtH4K")
Producer.create(name:"Toy and Sons",address:"Boyd",address2:"Kuching",county_id:29,contact_phone:"410-79-0410",contact_email:"mlinch1d@i2i.jp",password:"3rrf4M4TDl2"}