Product.create(name:"Longos - Chicken Wings",description:"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris",price:"9.68",enabled:true,deleted:false)
Product.create(name:"Crab - Soft Shell",description:"dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur",price:"4.74",enabled:true,deleted:false)
Product.create(name:"Chicken - Breast, 5 - 7 Oz",description:"pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit",price:"2.27",enabled:true,deleted:false)
Product.create(name:"Rolled Oats",description:"molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus",price:"3.74",enabled:true,deleted:false)
Product.create(name:"Longos - Grilled Salmon With Bbq",description:"tincidunt lacus at velit vivamus vel nulla eget eros elementum",price:"4.75",enabled:true,deleted:false)
Product.create(name:"Jam - Strawberry, 20 Ml Jar",description:"vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra",price:"2.53",enabled:true,deleted:false)
Product.create(name:"Chervil - Fresh",description:"cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec",price:"2.10",enabled:true,deleted:false)
Product.create(name:"V8 - Berry Blend",description:"cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu",price:"3.50",enabled:true,deleted:false)
Product.create(name:"Cocktail Napkin Blue",description:"donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque",price:"4.56",enabled:true,deleted:false)
Product.create(name:"Wine - Masi Valpolocell",description:"libero nullam sit amet turpis elementum ligula vehicula consequat morbi a",price:"6.95",enabled:true,deleted:false)
Product.create(name:"Nantucket Apple Juice",description:"quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices",price:"9.40",enabled:true,deleted:false)
Product.create(name:"Buffalo - Tenderloin",description:"ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit",price:"2.14",enabled:true,deleted:false)
Product.create(name:"Daves Island Stinger",description:"egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies",price:"2.38",enabled:true,deleted:false)
Product.create(name:"Watercress",description:"nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel",price:"3.08",enabled:true,deleted:false)
Product.create(name:"Walkers Special Old Whiskey",description:"eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae",price:"8.13",enabled:true,deleted:false)
Product.create(name:"Pepper - Black, Ground",description:"aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis",price:"7.61",enabled:true,deleted:false)
Product.create(name:"Icecream Bar - Del Monte",description:"morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus",price:"5.56",enabled:true,deleted:false)
Product.create(name:"Neckerchief Blck",description:"rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit",price:"2.60",enabled:true,deleted:false)
Product.create(name:"Flour - Buckwheat, Dark",description:"suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes",price:"7.03",enabled:true,deleted:false)
Product.create(name:"Pasta - Fettuccine, Dry",description:"felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat",price:"9.93",enabled:true,deleted:false)
Product.create(name:"Wine - Manischewitz Concord",description:"sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla",price:"9.21",enabled:true,deleted:false)
Product.create(name:"Flour - Chickpea",description:"non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc",price:"7.99",enabled:true,deleted:false)
Product.create(name:"Truffle Shells - White Chocolate",description:"turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris",price:"2.89",enabled:true,deleted:false)
Product.create(name:"Bread - Crusty Italian Poly",description:"non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque",price:"7.23",enabled:true,deleted:false)
Product.create(name:"Dates",description:"ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec",price:"7.90",enabled:true,deleted:false)
Product.create(name:"Syrup - Golden, Lyles",description:"ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",price:"3.89",enabled:true,deleted:false)
Product.create(name:"Mushroom - Shitake, Dry",description:"donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum",price:"2.65",enabled:true,deleted:false)
Product.create(name:"Longos - Chicken Curried",description:"ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id",price:"2.72",enabled:true,deleted:false)
Product.create(name:"White Baguette",description:"viverra pede ac diam cras pellentesque volutpat dui maecenas tristique",price:"7.21",enabled:true,deleted:false)
Product.create(name:"Wine - Chianti Classica Docg",description:"mattis nibh ligula nec sem duis aliquam convallis nunc proin at",price:"2.47",enabled:true,deleted:false)
Product.create(name:"Beef - Top Butt Aaa",description:"molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst",price:"7.76",enabled:true,deleted:false)
Product.create(name:"Wine - Saint - Bris 2002, Sauv",description:"curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec",price:"4.66",enabled:true,deleted:false)
Product.create(name:"Coffee Caramel Biscotti",description:"convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque",price:"4.29",enabled:true,deleted:false)
Product.create(name:"Soap - Hand Soap",description:"et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices",price:"4.10",enabled:true,deleted:false)
Product.create(name:"Wine - Segura Viudas Aria Brut",description:"gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget",price:"9.57",enabled:true,deleted:false)
Product.create(name:"Sesame Seed Black",description:"morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus",price:"9.49",enabled:true,deleted:false)
Product.create(name:"Bay Leaf Fresh",description:"ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie",price:"7.24",enabled:true,deleted:false)
Product.create(name:"Cheese - Cheddarsliced",description:"ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel",price:"4.43",enabled:true,deleted:false)
Product.create(name:"Tuna - Yellowfin",description:"aenean sit amet justo morbi ut odio cras mi pede malesuada",price:"7.68",enabled:true,deleted:false)
Product.create(name:"Turkey Leg With Drum And Thigh",description:"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",price:"9.26",enabled:true,deleted:false)
Product.create(name:"Vinegar - Cider",description:"luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat",price:"5.51",enabled:true,deleted:false)
Product.create(name:"Energy Drink Red Bull",description:"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices",price:"7.30",enabled:true,deleted:false)
Product.create(name:"Croissants Thaw And Serve",description:"aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas",price:"2.56",enabled:true,deleted:false)
Product.create(name:"Wine - Ruffino Chianti Classico",description:"viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec",price:"8.98",enabled:true,deleted:false)
Product.create(name:"Tea - Herbal Orange Spice",description:"etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi",price:"3.63",enabled:true,deleted:false)
Product.create(name:"Appetizer - Spring Roll, Veg",description:"justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla",price:"2.76",enabled:true,deleted:false)
Product.create(name:"Fennel",description:"quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",price:"8.66",enabled:true,deleted:false)
Product.create(name:"Chicken - Whole",description:"nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",price:"3.13",enabled:true,deleted:false)
Product.create(name:"Broom - Push",description:"hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem",price:"7.03",enabled:true,deleted:false)
Product.create(name:"Buffalo - Short Rib Fresh",description:"eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor",price:"3.79",enabled:true,deleted:false)
Product.create(name:"Sauce - Cranberry",description:"hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante",price:"3.88",enabled:true,deleted:false)
Product.create(name:"Chips Potato Salt Vinegar 43g",description:"dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum",price:"7.10",enabled:true,deleted:false)
Product.create(name:"Parsley - Dried",description:"tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci",price:"4.49",enabled:true,deleted:false)
Product.create(name:"Beans - Navy, Dry",description:"cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",price:"5.16",enabled:true,deleted:false)
Product.create(name:"Glass Clear 7 Oz Xl",description:"accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque",price:"7.60",enabled:true,deleted:false)
Product.create(name:"Buffalo - Striploin",description:"sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel",price:"8.49",enabled:true,deleted:false)
Product.create(name:"Salt - Celery",description:"cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae",price:"9.79",enabled:true,deleted:false)
Product.create(name:"Muffin - Bran Ind Wrpd",description:"nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum",price:"2.89",enabled:true,deleted:false)
Product.create(name:"Capon - Breast, Double, Wing On",description:"tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique",price:"6.65",enabled:true,deleted:false)
Product.create(name:"Coffee Cup 12oz 5342cd",description:"tempus semper est quam pharetra magna ac consequat metus sapien",price:"6.85",enabled:true,deleted:false)
Product.create(name:"Yoplait - Strawbrasp Peac",description:"consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id",price:"6.33",enabled:true,deleted:false)
Product.create(name:"Tea Leaves - Oolong",description:"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id",price:"9.31",enabled:true,deleted:false)
Product.create(name:"Soup Knorr Chili With Beans",description:"enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in",price:"3.50",enabled:true,deleted:false)
Product.create(name:"Tea - Decaf 1 Cup",description:"aliquam convallis nunc proin at turpis a pede posuere nonummy integer non",price:"2.09",enabled:true,deleted:false)
Product.create(name:"Snapple - Mango Maddness",description:"erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea",price:"4.35",enabled:true,deleted:false)
Product.create(name:"Lemon Balm - Fresh",description:"magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien",price:"7.13",enabled:true,deleted:false)
Product.create(name:"Wine La Vielle Ferme Cote Du",description:"vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet",price:"9.54",enabled:true,deleted:false)
Product.create(name:"Gherkin - Sour",description:"elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue",price:"3.83",enabled:true,deleted:false)
Product.create(name:"Vector Energy Bar",description:"semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus",price:"6.07",enabled:true,deleted:false)
Product.create(name:"Sparkling Wine - Rose, Freixenet",description:"in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla",price:"5.69",enabled:true,deleted:false)
Product.create(name:"Napkin - Cocktail,beige 2 - Ply",description:"morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed",price:"9.29",enabled:true,deleted:false)
Product.create(name:"Cheese - Gorgonzola",description:"amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo",price:"4.47",enabled:true,deleted:false)
Product.create(name:"Soup - Boston Clam Chowder",description:"orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum",price:"4.05",enabled:true,deleted:false)
Product.create(name:"Cinnamon Rolls",description:"cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",price:"2.89",enabled:true,deleted:false)
Product.create(name:"Wine - Soave Folonari",description:"vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis",price:"8.85",enabled:true,deleted:false)
Product.create(name:"Wine - Sauvignon Blanc",description:"sagittis dui vel nisl duis ac nibh fusce lacus purus",price:"2.00",enabled:true,deleted:false)
Product.create(name:"Bacardi Raspberry",description:"accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",price:"5.67",enabled:true,deleted:false)
Product.create(name:"Pasta - Shells, Medium, Dry",description:"turpis eget elit sodales scelerisque mauris sit amet eros suspendisse",price:"6.88",enabled:true,deleted:false)
Product.create(name:"Shiro Miso",description:"augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",price:"3.95",enabled:true,deleted:false)
Product.create(name:"Pop - Club Soda Can",description:"sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",price:"3.71",enabled:true,deleted:false)
Product.create(name:"Long Island Ice Tea",description:"ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer",price:"6.46",enabled:true,deleted:false)
Product.create(name:"Cheese - Pont Couvert",description:"primis in faucibus orci luctus et ultrices posuere cubilia curae donec",price:"3.21",enabled:true,deleted:false)
Product.create(name:"Rum - Light, Captain Morgan",description:"turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh",price:"6.80",enabled:true,deleted:false)
Product.create(name:"Veal Inside - Provimi",description:"eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui",price:"5.49",enabled:true,deleted:false)
Product.create(name:"Wine - Acient Coast Caberne",description:"vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed",price:"8.30",enabled:true,deleted:false)
Product.create(name:"Currants",description:"amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",price:"3.24",enabled:true,deleted:false)
Product.create(name:"Coconut - Whole",description:"in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula",price:"6.62",enabled:true,deleted:false)
Product.create(name:"Sprite, Diet - 355ml",description:"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae",price:"2.71",enabled:true,deleted:false)
Product.create(name:"Beer - Labatt Blue",description:"praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel",price:"6.63",enabled:true,deleted:false)
Product.create(name:"Bar Special K",description:"ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",price:"3.37",enabled:true,deleted:false)
Product.create(name:"Club Soda - Schweppes, 355 Ml",description:"orci luctus et ultrices posuere cubilia curae donec pharetra magna",price:"5.50",enabled:true,deleted:false)
Product.create(name:"Dill - Primerba, Paste",description:"blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula",price:"9.15",enabled:true,deleted:false)
Product.create(name:"Ice Cream - Fudge Bars",description:"libero nam dui proin leo odio porttitor id consequat in consequat",price:"6.27",enabled:true,deleted:false)
Product.create(name:"Turnip - Wax",description:"amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis",price:"9.27",enabled:true,deleted:false)
Product.create(name:"Wine - Ruffino Chianti",description:"scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante",price:"4.47",enabled:true,deleted:false)
Product.create(name:"Tabasco Sauce, 2 Oz",description:"arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in",price:"6.32",enabled:true,deleted:false)
Product.create(name:"Carrots - Mini Red Organic",description:"pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea",price:"4.07",enabled:true,deleted:false)
Product.create(name:"Spring Roll Wrappers",description:"id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",price:"9.43",enabled:true,deleted:false)
Product.create(name:"Bread - White, Unsliced",description:"faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor",price:"7.58",enabled:true,deleted:false)
Product.create(name:"Vinegar - Balsamic, White",description:"porttitor lorem id ligula suspendisse ornare consequat lectus in est risus",price:"3.80",enabled:true,deleted:false)
Product.create(name:"Bread Base - Toscano",description:"lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in",price:"6.76",enabled:true,deleted:false)
Product.create(name:"Chicken - Diced, Cooked",description:"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie",price:"9.14",enabled:true,deleted:false)
Product.create(name:"Ice Cream Bar - Oreo Sandwich",description:"lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea",price:"7.72",enabled:true,deleted:false)
Product.create(name:"Wine - Jackson Triggs Okonagan",description:"pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis",price:"3.55",enabled:true,deleted:false)
Product.create(name:"Lid - 0090 Clear",description:"donec dapibus duis at velit eu est congue elementum in hac",price:"4.07",enabled:true,deleted:false)
Product.create(name:"Onions - Spanish",description:"posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non",price:"3.97",enabled:true,deleted:false)
Product.create(name:"Tamarind Paste",description:"ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis",price:"3.40",enabled:true,deleted:false)
Product.create(name:"Coconut - Creamed, Pure",description:"semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus",price:"4.69",enabled:true,deleted:false)
Product.create(name:"Napkin - Beverage 1 Ply",description:"venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed",price:"8.78",enabled:true,deleted:false)
Product.create(name:"Yeast - Fresh, Fleischman",description:"donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan",price:"9.09",enabled:true,deleted:false)
Product.create(name:"Tarts Assorted",description:"vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est",price:"5.36",enabled:true,deleted:false)
Product.create(name:"Wine - White, Gewurtzraminer",description:"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque",price:"3.84",enabled:true,deleted:false)
Product.create(name:"Oil - Canola",description:"etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent",price:"3.59",enabled:true,deleted:false)
Product.create(name:"Chilli Paste, Sambal Oelek",description:"sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod",price:"5.83",enabled:true,deleted:false)
Product.create(name:"Cleaner - Bleach",description:"a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit",price:"5.86",enabled:true,deleted:false)
Product.create(name:"Pasta - Spaghetti, Dry",description:"sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla",price:"7.97",enabled:true,deleted:false)
Product.create(name:"Beef - Tenderlion, Center Cut",description:"ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at",price:"6.08",enabled:true,deleted:false)
Product.create(name:"Crab - Meat",description:"nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus",price:"8.20",enabled:true,deleted:false)
Product.create(name:"Oil - Sunflower",description:"tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit",price:"8.80",enabled:true,deleted:false)
Product.create(name:"Nestea - Ice Tea, Diet",description:"massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia",price:"6.83",enabled:true,deleted:false)
Product.create(name:"Appetizer - Veg Assortment",description:"consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero",price:"3.00",enabled:true,deleted:false)
Product.create(name:"Turkey - Breast, Smoked",description:"sit amet sem fusce consequat nulla nisl nunc nisl duis",price:"6.32",enabled:true,deleted:false)
Product.create(name:"Sauce - Cranberry",description:"sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at",price:"4.05",enabled:true,deleted:false)
Product.create(name:"Bouillion - Fish",description:"luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse",price:"2.91",enabled:true,deleted:false)
Product.create(name:"Pasta - Canelloni",description:"congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam",price:"7.98",enabled:true,deleted:false)
Product.create(name:"Tendrils - Baby Pea, Organic",description:"cras pellentesque volutpat dui maecenas tristique est et tempus semper est",price:"7.15",enabled:true,deleted:false)
Product.create(name:"Wine - Toasted Head",description:"at turpis a pede posuere nonummy integer non velit donec diam",price:"3.91",enabled:true,deleted:false)
Product.create(name:"Squash - Pepper",description:"nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan",price:"3.48",enabled:true,deleted:false)
Product.create(name:"Avocado",description:"orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit",price:"2.51",enabled:true,deleted:false)
Product.create(name:"Whmis - Spray Bottle Trigger",description:"sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan",price:"4.96",enabled:true,deleted:false)
Product.create(name:"Puff Pastry - Slab",description:"vulputate justo in blandit ultrices enim lorem ipsum dolor sit",price:"4.25",enabled:true,deleted:false)
Product.create(name:"Vinegar - Red Wine",description:"in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas",price:"4.69",enabled:true,deleted:false)
Product.create(name:"Gelatine Leaves - Envelopes",description:"sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo",price:"6.95",enabled:true,deleted:false)
Product.create(name:"Veal - Liver",description:"semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum",price:"7.98",enabled:true,deleted:false)
Product.create(name:"Tea Peppermint",description:"dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent",price:"7.64",enabled:true,deleted:false)
Product.create(name:"Chutney Sauce",description:"donec dapibus duis at velit eu est congue elementum in",price:"6.76",enabled:true,deleted:false)
Product.create(name:"Veal - Insides Provini",description:"tortor id nulla ultrices aliquet maecenas leo odio condimentum id",price:"6.91",enabled:true,deleted:false)
Product.create(name:"Bread Roll Foccacia",description:"aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",price:"8.97",enabled:true,deleted:false)
Product.create(name:"Garbage Bags - Black",description:"lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",price:"5.48",enabled:true,deleted:false)
Product.create(name:"Pepper - Paprika, Spanish",description:"et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis",price:"2.74",enabled:true,deleted:false)
Product.create(name:"Capon - Breast, Wing On",description:"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",price:"9.89",enabled:true,deleted:false)
Product.create(name:"Beans - Wax",description:"lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",price:"4.08",enabled:true,deleted:false)
Product.create(name:"Vermouth - Sweet, Cinzano",description:"diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque",price:"6.71",enabled:true,deleted:false)
Product.create(name:"Bread - Malt",description:"convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim",price:"5.49",enabled:true,deleted:false)
Product.create(name:"Five Alive Citrus",description:"ut nulla sed accumsan felis ut at dolor quis odio consequat varius",price:"3.30",enabled:true,deleted:false)
Product.create(name:"Veal - Osso Bucco",description:"turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut",price:"2.60",enabled:true,deleted:false)
Product.create(name:"Beer - Sleemans Cream Ale",description:"ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo",price:"8.75",enabled:true,deleted:false)
Product.create(name:"Nantucket - Orange Mango Cktl",description:"pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate",price:"6.49",enabled:true,deleted:false)
Product.create(name:"Lobster - Cooked",description:"morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel",price:"6.36",enabled:true,deleted:false)
Product.create(name:"Pepper - Red, Finger Hot",description:"consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius",price:"7.20",enabled:true,deleted:false)
Product.create(name:"Shallots",description:"quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis",price:"3.96",enabled:true,deleted:false)
Product.create(name:"Blueberries",description:"nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",price:"9.22",enabled:true,deleted:false)
Product.create(name:"Lime Cordial - Roses",description:"vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis",price:"6.67",enabled:true,deleted:false)
Product.create(name:"Sandwich Wrap",description:"quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis",price:"2.88",enabled:true,deleted:false)
Product.create(name:"Flower - Leather Leaf Fern",description:"sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc",price:"7.49",enabled:true,deleted:false)
Product.create(name:"External Supplier",description:"maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien",price:"7.48",enabled:true,deleted:false)
Product.create(name:"Lemonade - Natural, 591 Ml",description:"sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae",price:"2.15",enabled:true,deleted:false)
Product.create(name:"Green Scrubbie Pad H.duty",description:"volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc",price:"5.35",enabled:true,deleted:false)
Product.create(name:"Cheese - Woolwich Goat, Log",description:"eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper",price:"7.90",enabled:true,deleted:false)
Product.create(name:"Pork Ham Prager",description:"leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis",price:"6.09",enabled:true,deleted:false)
Product.create(name:"Sultanas",description:"sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna",price:"5.36",enabled:true,deleted:false)
Product.create(name:"Myers Planters Punch",description:"duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse",price:"6.48",enabled:true,deleted:false)
Product.create(name:"Absolut Citron",description:"at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel",price:"7.53",enabled:true,deleted:false)
Product.create(name:"Shrimp - 100 / 200 Cold Water",description:"a odio in hac habitasse platea dictumst maecenas ut massa quis augue",price:"8.23",enabled:true,deleted:false)
Product.create(name:"Beef - Top Butt Aaa",description:"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",price:"2.94",enabled:true,deleted:false)
Product.create(name:"Pastry - Baked Cinnamon Stick",description:"et tempus semper est quam pharetra magna ac consequat metus sapien",price:"3.88",enabled:true,deleted:false)
Product.create(name:"Wine - White, Pelee Island",description:"libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas",price:"7.61",enabled:true,deleted:false)
Product.create(name:"Cinnamon Rolls",description:"donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu",price:"9.77",enabled:true,deleted:false)
Product.create(name:"Tea - Camomele",description:"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis",price:"2.77",enabled:true,deleted:false)
Product.create(name:"Zucchini - Green",description:"orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor",price:"3.64",enabled:true,deleted:false)
Product.create(name:"Wine - White, Pelee Island",description:"quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus",price:"3.48",enabled:true,deleted:false)
Product.create(name:"Mushrooms - Black, Dried",description:"mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus",price:"8.05",enabled:true,deleted:false)
Product.create(name:"Puree - Strawberry",description:"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum",price:"8.05",enabled:true,deleted:false)
Product.create(name:"Soup - Knorr, Chicken Gumbo",description:"interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices",price:"9.20",enabled:true,deleted:false)
Product.create(name:"Squash - Sunburst",description:"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia",price:"3.60",enabled:true,deleted:false)
Product.create(name:"Bar Nature Valley",description:"quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id",price:"4.12",enabled:true,deleted:false)
Product.create(name:"Calvados - Boulard",description:"erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus",price:"2.26",enabled:true,deleted:false)
Product.create(name:"Flax Seed",description:"ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor",price:"6.52",enabled:true,deleted:false)
Product.create(name:"Steel Wool",description:"maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",price:"6.51",enabled:true,deleted:false)
Product.create(name:"Chinese Lemon Pork",description:"vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque",price:"2.69",enabled:true,deleted:false)
Product.create(name:"Appetizer - Shrimp Puff",description:"semper rutrum nulla nunc purus phasellus in felis donec semper",price:"6.18",enabled:true,deleted:false)
Product.create(name:"Wine - Tribal Sauvignon",description:"molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat",price:"7.39",enabled:true,deleted:false)
Product.create(name:"Beef - Cow Feet Split",description:"sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl",price:"4.41",enabled:true,deleted:false)
Product.create(name:"Teriyaki Sauce",description:"pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat",price:"8.40",enabled:true,deleted:false)
Product.create(name:"Muffin Hinge Container 6",description:"nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula",price:"9.55",enabled:true,deleted:false)
Product.create(name:"Soup - Clam Chowder, Dry Mix",description:"nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas",price:"5.45",enabled:true,deleted:false)
Product.create(name:"Ecolab - Ster Bac",description:"dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus",price:"7.00",enabled:true,deleted:false)
Product.create(name:"Wine - Delicato Merlot",description:"mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",price:"7.58",enabled:true,deleted:false)
Product.create(name:"Lychee - Canned",description:"hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer",price:"8.45",enabled:true,deleted:false)
Product.create(name:"Cheese - Goat",description:"nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed",price:"3.96",enabled:true,deleted:false)
Product.create(name:"Pork - Chop, Frenched",description:"eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras",price:"3.15",enabled:true,deleted:false)
Product.create(name:"Lotus Root",description:"potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur",price:"2.23",enabled:true,deleted:false)
Product.create(name:"Glass Clear 7 Oz Xl",description:"eget congue eget semper rutrum nulla nunc purus phasellus in felis",price:"7.90",enabled:true,deleted:false)
Product.create(name:"Pastry - Cheese Baked Scones",description:"proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in",price:"2.03",enabled:true,deleted:false)
Product.create(name:"Brandy Cherry - Mcguinness",description:"faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit",price:"7.13",enabled:true,deleted:false)
Product.create(name:"Flavouring - Raspberry",description:"eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis",price:"9.36",enabled:true,deleted:false)
Product.create(name:"Coffee - Hazelnut Cream",description:"curabitur in libero ut massa volutpat convallis morbi odio odio elementum",price:"6.03",enabled:true,deleted:false)
Product.create(name:"Sprite, Diet - 355ml",description:"hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget",price:"6.48",enabled:true,deleted:false)
Product.create(name:"Cake - Miini Cheesecake Cherry",description:"fusce congue diam id ornare imperdiet sapien urna pretium nisl ut",price:"5.00",enabled:true,deleted:false)
Product.create(name:"Nescafe - Frothy French Vanilla",description:"ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo",price:"5.51",enabled:true,deleted:false)
Product.create(name:"Gingerale - Schweppes, 355 Ml",description:"orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae",price:"3.34",enabled:true,deleted:false)
Product.create(name:"Cardamon Seed / Pod",description:"ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin",price:"4.78",enabled:true,deleted:false)
Product.create(name:"Rabbit - Whole",description:"id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate",price:"5.59",enabled:true,deleted:false)
Product.create(name:"Wine - Niagara,vqa Reisling",description:"est donec odio justo sollicitudin ut suscipit a feugiat et eros",price:"8.69",enabled:true,deleted:false)
Product.create(name:"Calypso - Strawberry Lemonade",description:"lorem id ligula suspendisse ornare consequat lectus in est risus",price:"9.26",enabled:true,deleted:false)
Product.create(name:"Vermacelli - Sprinkles, Assorted",description:"justo etiam pretium iaculis justo in hac habitasse platea dictumst",price:"5.32",enabled:true,deleted:false)
Product.create(name:"Beer - Maudite",description:"quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus",price:"6.53",enabled:true,deleted:false)
Product.create(name:"Star Fruit",description:"leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet",price:"2.60",enabled:true,deleted:false)
Product.create(name:"Catfish - Fillets",description:"in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",price:"8.78",enabled:true,deleted:false)
Product.create(name:"Pineapple - Canned, Rings",description:"lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non",price:"3.75",enabled:true,deleted:false)
Product.create(name:"Island Oasis - Pina Colada",description:"praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede",price:"7.84",enabled:true,deleted:false)
Product.create(name:"Veal - Ground",description:"platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum",price:"5.33",enabled:true,deleted:false)
Product.create(name:"Mustard - Dijon",description:"nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros",price:"3.19",enabled:true,deleted:false)
Product.create(name:"Bread - Raisin Walnut Pull",description:"vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu",price:"6.57",enabled:true,deleted:false)
Product.create(name:"Napkin Colour",description:"curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla",price:"6.01",enabled:true,deleted:false)
Product.create(name:"Icecream Bar - Del Monte",description:"volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper",price:"8.77",enabled:true,deleted:false)
Product.create(name:"Contreau",description:"mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus",price:"4.59",enabled:true,deleted:false)
Product.create(name:"Oregano - Fresh",description:"luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis",price:"6.74",enabled:true,deleted:false)
Product.create(name:"Broom - Push",description:"erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a",price:"5.21",enabled:true,deleted:false)
Product.create(name:"Potatoes - Yukon Gold, 80 Ct",description:"eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor",price:"7.56",enabled:true,deleted:false)
Product.create(name:"Cup - 4oz Translucent",description:"interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa",price:"2.60",enabled:true,deleted:false)
Product.create(name:"Scallops - 20/30",description:"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor",price:"7.45",enabled:true,deleted:false)
Product.create(name:"Wine - Zinfandel Rosenblum",description:"molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",price:"3.03",enabled:true,deleted:false)
Product.create(name:"Mince Meat - Filling",description:"quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer",price:"9.14",enabled:true,deleted:false)
Product.create(name:"Steam Pan Full Lid",description:"erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque",price:"2.29",enabled:true,deleted:false)
Product.create(name:"Cookie Dough - Chunky",description:"turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum",price:"5.29",enabled:true,deleted:false)
Product.create(name:"Appetizer - Assorted Box",description:"sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam",price:"5.06",enabled:true,deleted:false)
Product.create(name:"Pasta - Lasagna Noodle, Frozen",description:"in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis",price:"5.49",enabled:true,deleted:false)
Product.create(name:"Onions - Dried, Chopped",description:"lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis",price:"7.01",enabled:true,deleted:false)
Product.create(name:"Rum - Coconut, Malibu",description:"velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum",price:"6.82",enabled:true,deleted:false)
Product.create(name:"Cheese - Mozzarella, Buffalo",description:"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi",price:"2.89",enabled:true,deleted:false)
Product.create(name:"Lamb Rack - Ontario",description:"feugiat non pretium quis lectus suspendisse potenti in eleifend quam a",price:"4.58",enabled:true,deleted:false)
Product.create(name:"Syrup - Monin, Swiss Choclate",description:"a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id",price:"5.63",enabled:true,deleted:false)
Product.create(name:"Pop - Club Soda Can",description:"bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa",price:"6.77",enabled:true,deleted:false)
Product.create(name:"Parsley - Fresh",description:"sed augue aliquam erat volutpat in congue etiam justo etiam pretium",price:"6.59",enabled:true,deleted:false)
Product.create(name:"Nut - Pumpkin Seeds",description:"imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus",price:"4.17",enabled:true,deleted:false)
Product.create(name:"Syrup - Monin - Blue Curacao",description:"vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros",price:"3.21",enabled:true,deleted:false)
Product.create(name:"Tea Leaves - Oolong",description:"magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum",price:"9.97",enabled:true,deleted:false)
Product.create(name:"Scallops - Live In Shell",description:"consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna",price:"2.72",enabled:true,deleted:false)
Product.create(name:"V8 Splash Strawberry Banana",description:"nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",price:"9.80",enabled:true,deleted:false)
Product.create(name:"Wine - Chianti Classica Docg",description:"justo eu massa donec dapibus duis at velit eu est congue",price:"2.11",enabled:true,deleted:false)
Product.create(name:"Juice - Mango",description:"augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices",price:"7.34",enabled:true,deleted:false)
Product.create(name:"Pork - Sausage, Medium",description:"vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum",price:"9.11",enabled:true,deleted:false)
Product.create(name:"Salt - Kosher",description:"scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin",price:"5.92",enabled:true,deleted:false)
Product.create(name:"Plasticknivesblack",description:"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla",price:"8.36",enabled:true,deleted:false)
Product.create(name:"Pate - Peppercorn",description:"at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit",price:"9.78",enabled:true,deleted:false)
Product.create(name:"Sausage - Breakfast",description:"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis",price:"5.77",enabled:true,deleted:false)
Product.create(name:"Soup - Campbells, Minestrone",description:"lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis",price:"7.87",enabled:true,deleted:false)
Product.create(name:"Relish",description:"maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum",price:"6.13",enabled:true,deleted:false)
Product.create(name:"Asparagus - White, Fresh",description:"ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",price:"7.24",enabled:true,deleted:false)
Product.create(name:"Syrup - Golden, Lyles",description:"at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea",price:"5.57",enabled:true,deleted:false)
Product.create(name:"Muffin Hinge 117n",description:"at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed",price:"2.15",enabled:true,deleted:false)
Product.create(name:"Sprouts - Alfalfa",description:"elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas",price:"4.06",enabled:true,deleted:false)
Product.create(name:"Red Pepper Paste",description:"turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",price:"3.45",enabled:true,deleted:false)
Product.create(name:"Tea - Herbal I Love Lemon",description:"vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur",price:"5.87",enabled:true,deleted:false)
Product.create(name:"Creme De Menth - White",description:"aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas",price:"9.44",enabled:true,deleted:false)
Product.create(name:"Raisin - Golden",description:"etiam faucibus cursus urna ut tellus nulla ut erat id mauris",price:"2.81",enabled:true,deleted:false)
Product.create(name:"Water - Tonic",description:"at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium",price:"6.94",enabled:true,deleted:false)
Product.create(name:"Plate - Foam, Bread And Butter",description:"est congue elementum in hac habitasse platea dictumst morbi vestibulum velit",price:"4.28",enabled:true,deleted:false)
Product.create(name:"Sugar - Splenda Sweetener",description:"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu",price:"3.20",enabled:true,deleted:false)
Product.create(name:"Island Oasis - Magarita Mix",description:"nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices",price:"6.15",enabled:true,deleted:false)
Product.create(name:"Bay Leaf Ground",description:"gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada",price:"4.41",enabled:true,deleted:false)
Product.create(name:"Fruit Mix - Light",description:"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis",price:"7.97",enabled:true,deleted:false)
Product.create(name:"Spinach - Baby",description:"elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue",price:"6.67",enabled:true,deleted:false)
Product.create(name:"Pork - Bones",description:"orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in",price:"8.92",enabled:true,deleted:false)
Product.create(name:"Cheese - Grana Padano",description:"vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",price:"3.61",enabled:true,deleted:false)
Product.create(name:"Cheese - Victor Et Berthold",description:"sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices",price:"6.05",enabled:true,deleted:false)
Product.create(name:"Chinese Foods - Cantonese",description:"nec dui luctus rutrum nulla tellus in sagittis dui vel nisl",price:"2.03",enabled:true,deleted:false)
Product.create(name:"Vinegar - Sherry",description:"lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea",price:"2.77",enabled:true,deleted:false)
Product.create(name:"Nut - Pecan, Pieces",description:"porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse",price:"7.20",enabled:true,deleted:false)
Product.create(name:"Table Cloth 53x53 White",description:"ultrices mattis odio donec vitae nisi nam ultrices libero non mattis",price:"4.66",enabled:true,deleted:false)
Product.create(name:"Wine - Beringer Founders Estate",description:"scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed",price:"2.08",enabled:true,deleted:false)
Product.create(name:"Ham - Cooked",description:"suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus",price:"6.28",enabled:true,deleted:false)
Product.create(name:"Aspic - Clear",description:"pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",price:"6.56",enabled:true,deleted:false)
Product.create(name:"Tuna - Loin",description:"aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan",price:"5.73",enabled:true,deleted:false)
Product.create(name:"Steampan Lid",description:"non mi integer ac neque duis bibendum morbi non quam nec dui",price:"9.18",enabled:true,deleted:false)
Product.create(name:"Cinnamon Rolls",description:"suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus",price:"7.82",enabled:true,deleted:false)
Product.create(name:"Swiss Chard",description:"nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",price:"5.60",enabled:true,deleted:false)
Product.create(name:"Appetizer - Veg Assortment",description:"nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin",price:"3.23",enabled:true,deleted:false)
Product.create(name:"Puree - Guava",description:"dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh",price:"4.70",enabled:true,deleted:false)
Product.create(name:"Bacardi Breezer - Tropical",description:"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus",price:"4.73",enabled:true,deleted:false)
Product.create(name:"Wine - Harrow Estates, Vidal",description:"quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus",price:"7.64",enabled:true,deleted:false)
Product.create(name:"Danishes - Mini Raspberry",description:"sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",price:"7.36",enabled:true,deleted:false)
Product.create(name:"Sauce - Sesame Thai Dressing",description:"luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur",price:"6.86",enabled:true,deleted:false)
Product.create(name:"Container Clear 8 Oz",description:"sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus",price:"5.12",enabled:true,deleted:false)
Product.create(name:"Soup - Tomato Mush. Florentine",description:"sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede",price:"8.47",enabled:true,deleted:false)
Product.create(name:"Coffee Cup 8oz 5338cd",description:"vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",price:"4.59",enabled:true,deleted:false)
Product.create(name:"Veal - Striploin",description:"id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui",price:"6.83",enabled:true,deleted:false)
Product.create(name:"Danishes - Mini Cheese",description:"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus",price:"6.06",enabled:true,deleted:false)
Product.create(name:"Piping - Bags Quizna",description:"a odio in hac habitasse platea dictumst maecenas ut massa quis",price:"4.67",enabled:true,deleted:false)
Product.create(name:"Juice - V8 Splash",description:"erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",price:"9.18",enabled:true,deleted:false)
Product.create(name:"Coconut - Shredded, Sweet",description:"molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus",price:"7.44",enabled:true,deleted:false)
Product.create(name:"Beans - Yellow",description:"vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan",price:"6.21",enabled:true,deleted:false)
Product.create(name:"Water - San Pellegrino",description:"sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",price:"3.31",enabled:true,deleted:false)
Product.create(name:"Beef - Ground, Extra Lean, Fresh",description:"sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",price:"7.32",enabled:true,deleted:false)
Product.create(name:"Spice - Montreal Steak Spice",description:"eget nunc donec quis orci eget orci vehicula condimentum curabitur",price:"6.59",enabled:true,deleted:false)
Product.create(name:"Lamb - Leg, Bone In",description:"varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",price:"7.30",enabled:true,deleted:false)
Product.create(name:"Tea - Vanilla Chai",description:"imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue",price:"7.51",enabled:true,deleted:false)
Product.create(name:"Shiro Miso",description:"metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci",price:"8.91",enabled:true,deleted:false)
Product.create(name:"Salmon Steak - Cohoe 6 Oz",description:"lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis",price:"3.35",enabled:true,deleted:false)
Product.create(name:"Pork - Loin, Center Cut",description:"dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est",price:"8.84",enabled:true,deleted:false)
Product.create(name:"Mustard - Pommery",description:"augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",price:"6.82",enabled:true,deleted:false)
Product.create(name:"Beer - Maudite",description:"erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",price:"8.80",enabled:true,deleted:false)
Product.create(name:"Red Currant Jelly",description:"vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",price:"8.19",enabled:true,deleted:false)
Product.create(name:"Beets - Candy Cane, Organic",description:"magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus",price:"3.94",enabled:true,deleted:false)
Product.create(name:"Cookie - Dough Variety",description:"vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique",price:"3.31",enabled:true,deleted:false)
Product.create(name:"Tart - Pecan Butter Squares",description:"at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel",price:"4.70",enabled:true,deleted:false)
Product.create(name:"Breakfast Quesadillas",description:"ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor",price:"5.77",enabled:true,deleted:false)
Product.create(name:"Cheese - Brie, Cups 125g",description:"congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo",price:"9.98",enabled:true,deleted:false)
Product.create(name:"Yucca",description:"sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu",price:"4.45",enabled:true,deleted:false)
Product.create(name:"Bread - Pullman, Sliced",description:"massa volutpat convallis morbi odio odio elementum eu interdum eu",price:"2.28",enabled:true,deleted:false)
Product.create(name:"Nantucket Pine Orangebanana",description:"at nunc commodo placerat praesent blandit nam nulla integer pede",price:"7.34",enabled:true,deleted:false)
Product.create(name:"Table Cloth 90x90 White",description:"consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi",price:"8.16",enabled:true,deleted:false)
Product.create(name:"Smirnoff Green Apple Twist",description:"aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede",price:"6.48",enabled:true,deleted:false)
Product.create(name:"Beans - Butter Lrg Lima",description:"cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis",price:"7.94",enabled:true,deleted:false)
Product.create(name:"Island Oasis - Ice Cream Mix",description:"volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea",price:"8.51",enabled:true,deleted:false)
Product.create(name:"Bread - Calabrese Baguette",description:"cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod",price:"4.52",enabled:true,deleted:false)
Product.create(name:"Eggwhite Frozen",description:"fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",price:"2.33",enabled:true,deleted:false)
Product.create(name:"Pastry - Key Limepoppy Seed Tea",description:"id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit",price:"5.53",enabled:true,deleted:false)
Product.create(name:"Plastic Wrap",description:"vulputate ut ultrices vel augue vestibulum ante ipsum primis in",price:"3.13",enabled:true,deleted:false)
Product.create(name:"Potato - Sweet",description:"habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",price:"7.12",enabled:true,deleted:false)
Product.create(name:"Tomatoes Tear Drop Yellow",description:"donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis",price:"8.41",enabled:true,deleted:false)
Product.create(name:"Chocolate - Unsweetened",description:"bibendum morbi non quam nec dui luctus rutrum nulla tellus",price:"2.36",enabled:true,deleted:false)
Product.create(name:"Cake - Cake Sheet Macaroon",description:"non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis",price:"7.11",enabled:true,deleted:false)
Product.create(name:"Spic And Span All Purpose",description:"non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus",price:"9.25",enabled:true,deleted:false)
Product.create(name:"Wine - White, Cooking",description:"tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",price:"4.31",enabled:true,deleted:false)
Product.create(name:"Wonton Wrappers",description:"mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non",price:"5.72",enabled:true,deleted:false)
Product.create(name:"Egg Patty Fried",description:"semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci",price:"2.25",enabled:true,deleted:false)
Product.create(name:"Cheese - Parmigiano Reggiano",description:"libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in",price:"8.36",enabled:true,deleted:false)
Product.create(name:"Ice Cream - Chocolate",description:"ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien",price:"2.85",enabled:true,deleted:false)
Product.create(name:"Soup - French Onion",description:"montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean",price:"3.74",enabled:true,deleted:false)
Product.create(name:"Pork - Ground",description:"volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",price:"2.75",enabled:true,deleted:false)
Product.create(name:"Poppy Seed",description:"et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus",price:"9.96",enabled:true,deleted:false)
Product.create(name:"Chick Peas - Canned",description:"non sodales sed tincidunt eu felis fusce posuere felis sed lacus",price:"6.02",enabled:true,deleted:false)
Product.create(name:"Pork - Back Ribs",description:"non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci",price:"7.76",enabled:true,deleted:false)
Product.create(name:"Cherries - Maraschino,jar",description:"erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis",price:"3.40",enabled:true,deleted:false)
Product.create(name:"Blueberries - Frozen",description:"et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in",price:"3.96",enabled:true,deleted:false)
Product.create(name:"Pepperoni Slices",description:"est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc",price:"6.02",enabled:true,deleted:false)
Product.create(name:"Beef - Shank",description:"sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed",price:"4.32",enabled:true,deleted:false)
Product.create(name:"Wine - Manischewitz Concord",description:"vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla",price:"7.90",enabled:true,deleted:false)
Product.create(name:"Beef - Short Loin",description:"sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula",price:"3.72",enabled:true,deleted:false)
Product.create(name:"Ice Cream Bar - Rolo Cone",description:"velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget",price:"6.57",enabled:true,deleted:false)
Product.create(name:"Cheese - Fontina",description:"suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris",price:"9.28",enabled:true,deleted:false)
Product.create(name:"Piping - Bags Quizna",description:"ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum",price:"4.51",enabled:true,deleted:false)
Product.create(name:"Lemons",description:"nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor",price:"4.70",enabled:true,deleted:false)
Product.create(name:"Syrup - Monin, Amaretta",description:"nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at",price:"7.02",enabled:true,deleted:false)
Product.create(name:"Pork - Bones",description:"porta volutpat quam pede lobortis ligula sit amet eleifend pede",price:"2.70",enabled:true,deleted:false)
Product.create(name:"Glucose",description:"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",price:"5.29",enabled:true,deleted:false)
Product.create(name:"French Pastries",description:"gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",price:"6.18",enabled:true,deleted:false)
Product.create(name:"Sauce - Balsamic Viniagrette",description:"iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante",price:"4.72",enabled:true,deleted:false)
Product.create(name:"Hog / Sausage Casing - Pork",description:"risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus",price:"4.95",enabled:true,deleted:false)
Product.create(name:"Scallop - St. Jaques",description:"pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed",price:"6.24",enabled:true,deleted:false)
Product.create(name:"Sun - Dried Tomatoes",description:"nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia",price:"8.68",enabled:true,deleted:false)
Product.create(name:"Beer - Pilsner Urquell",description:"in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",price:"5.00",enabled:true,deleted:false)
Product.create(name:"Cheese Cloth No 60",description:"in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam",price:"8.84",enabled:true,deleted:false)
Product.create(name:"Beef Dry Aged Tenderloin Aaa",description:"praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus",price:"3.19",enabled:true,deleted:false)
Product.create(name:"Beef - Rouladin, Sliced",description:"nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in",price:"7.11",enabled:true,deleted:false)
Product.create(name:"Turnip - White",description:"nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam",price:"9.09",enabled:true,deleted:false)
Product.create(name:"Chicken - Leg, Fresh",description:"praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum",price:"3.52",enabled:true,deleted:false)
Product.create(name:"Mint - Fresh",description:"aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede",price:"3.21",enabled:true,deleted:false)
Product.create(name:"Kahlua",description:"elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",price:"5.88",enabled:true,deleted:false)
Product.create(name:"Vodka - Smirnoff",description:"nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in",price:"2.26",enabled:true,deleted:false)
Product.create(name:"Lime Cordial - Roses",description:"elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",price:"8.52",enabled:true,deleted:false)
Product.create(name:"Chicken - Diced, Cooked",description:"adipiscing elit proin risus praesent lectus vestibulum quam sapien varius",price:"3.92",enabled:true,deleted:false)
Product.create(name:"Sausage - Andouille",description:"imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue",price:"9.58",enabled:true,deleted:false)
Product.create(name:"Yogurt - Blueberry, 175 Gr",description:"eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis",price:"6.14",enabled:true,deleted:false)
Product.create(name:"Wine - Cotes Du Rhone",description:"nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor",price:"6.88",enabled:true,deleted:false)
Product.create(name:"Haggis",description:"pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed",price:"4.72",enabled:true,deleted:false)
Product.create(name:"Sauce - Gravy, Au Jus, Mix",description:"pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est",price:"9.98",enabled:true,deleted:false)
Product.create(name:"Syrup - Pancake",description:"in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis",price:"8.59",enabled:true,deleted:false)
Product.create(name:"Paper Towel Touchless",description:"nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate",price:"4.56",enabled:true,deleted:false)
Product.create(name:"Greens Mustard",description:"neque libero convallis eget eleifend luctus ultricies eu nibh quisque id",price:"2.57",enabled:true,deleted:false)
Product.create(name:"Versatainer Nc - 9388",description:"in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",price:"6.55",enabled:true,deleted:false)
Product.create(name:"Plaintain",description:"ipsum primis in faucibus orci luctus et ultrices posuere cubilia",price:"3.75",enabled:true,deleted:false)
Product.create(name:"Lotus Rootlets - Canned",description:"erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper",price:"3.79",enabled:true,deleted:false)
Product.create(name:"Baking Powder",description:"justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus",price:"8.42",enabled:true,deleted:false)
Product.create(name:"Muffin Orange Individual",description:"dolor sit amet consectetuer adipiscing elit proin interdum mauris non",price:"4.03",enabled:true,deleted:false)
Product.create(name:"Cake - Bande Of Fruit",description:"semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante",price:"7.41",enabled:true,deleted:false)
Product.create(name:"Brandy - Orange, Mc Guiness",description:"nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam",price:"9.25",enabled:true,deleted:false)
Product.create(name:"Noodles - Cellophane, Thin",description:"tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet",price:"6.16",enabled:true,deleted:false)
Product.create(name:"Sambuca Cream",description:"libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut",price:"2.57",enabled:true,deleted:false)
Product.create(name:"Wine - Red, Gallo, Merlot",description:"amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",price:"7.11",enabled:true,deleted:false)
Product.create(name:"Lemon Pepper",description:"faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat",price:"2.95",enabled:true,deleted:false)
Product.create(name:"Pickerel - Fillets",description:"et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis",price:"4.29",enabled:true,deleted:false)
Product.create(name:"Rice - 7 Grain Blend",description:"nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",price:"3.82",enabled:true,deleted:false)
Product.create(name:"Trueblue - Blueberry Cranberry",description:"habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum",price:"6.70",enabled:true,deleted:false)
Product.create(name:"Wine - White, Pinot Grigio",description:"venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl",price:"4.58",enabled:true,deleted:false)
Product.create(name:"Wine - Sicilia Igt Nero Avola",description:"rutrum nulla nunc purus phasellus in felis donec semper sapien a",price:"2.68",enabled:true,deleted:false)
Product.create(name:"Grapefruit - White",description:"amet diam in magna bibendum imperdiet nullam orci pede venenatis non",price:"5.40",enabled:true,deleted:false)
Product.create(name:"Capon - Breast, Wing On",description:"ligula in lacus curabitur at ipsum ac tellus semper interdum mauris",price:"8.88",enabled:true,deleted:false)
Product.create(name:"Bay Leaf",description:"elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus",price:"9.08",enabled:true,deleted:false)
Product.create(name:"Puree - Mocha",description:"curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum",price:"3.33",enabled:true,deleted:false)
Product.create(name:"Wine - Cahors Ac 2000, Clos",description:"quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non",price:"8.09",enabled:true,deleted:false)
Product.create(name:"Ecolab - Ster Bac",description:"mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere",price:"5.39",enabled:true,deleted:false)
Product.create(name:"Wine - White, Pelee Island",description:"eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus",price:"8.01",enabled:true,deleted:false)
Product.create(name:"Bouq All Italian - Primerba",description:"suspendisse potenti cras in purus eu magna vulputate luctus cum",price:"9.70",enabled:true,deleted:false)
Product.create(name:"Flower - Commercial Spider",description:"donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer",price:"2.51",enabled:true,deleted:false)
Product.create(name:"Edible Flower - Mixed",description:"amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse",price:"6.76",enabled:true,deleted:false)
Product.create(name:"Grapefruit - Pink",description:"id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi",price:"4.43",enabled:true,deleted:false)
Product.create(name:"Table Cloth 54x72 White",description:"amet erat nulla tempus vivamus in felis eu sapien cursus",price:"2.64",enabled:true,deleted:false)
Product.create(name:"Egg Patty Fried",description:"sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis",price:"2.03",enabled:true,deleted:false)
Product.create(name:"Peas - Pigeon, Dry",description:"accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam",price:"2.21",enabled:true,deleted:false)
Product.create(name:"Pepperoni Slices",description:"eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae",price:"9.15",enabled:true,deleted:false)
Product.create(name:"Salt - Seasoned",description:"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",price:"5.17",enabled:true,deleted:false)
Product.create(name:"Ice Cream - Turtles Stick Bar",description:"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",price:"7.09",enabled:true,deleted:false)
Product.create(name:"Pork - Loin, Center Cut",description:"consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla",price:"3.08",enabled:true,deleted:false)
Product.create(name:"V8 - Tropical Blend",description:"accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula",price:"4.76",enabled:true,deleted:false)
Product.create(name:"Shrimp - Baby, Warm Water",description:"dui vel nisl duis ac nibh fusce lacus purus aliquet",price:"8.11",enabled:true,deleted:false)
Product.create(name:"Milkettes - 2%",description:"pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus",price:"7.72",enabled:true,deleted:false)
Product.create(name:"Taro Root",description:"odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar",price:"6.54",enabled:true,deleted:false)
Product.create(name:"Creme De Banane - Marie",description:"id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam",price:"6.91",enabled:true,deleted:false)
Product.create(name:"Beans - Yellow",description:"augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero",price:"8.94",enabled:true,deleted:false)
Product.create(name:"Pasta - Shells, Medium, Dry",description:"quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus",price:"7.75",enabled:true,deleted:false)
Product.create(name:"Mousse - Mango",description:"eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus",price:"4.23",enabled:true,deleted:false)
Product.create(name:"Cocoa Powder - Natural",description:"in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien",price:"8.74",enabled:true,deleted:false)
Product.create(name:"Lid Coffeecup 12oz D9542b",description:"faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse",price:"9.07",enabled:true,deleted:false)
Product.create(name:"Oats Large Flake",description:"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi",price:"6.12",enabled:true,deleted:false)
Product.create(name:"Sugar - Fine",description:"nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis",price:"9.85",enabled:true,deleted:false)
Product.create(name:"Dish Towel",description:"massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id",price:"7.33",enabled:true,deleted:false)
Product.create(name:"Wine - Gewurztraminer Pierre",description:"pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla",price:"2.01",enabled:true,deleted:false)
Product.create(name:"The Pop Shoppe Pinapple",description:"quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti",price:"3.40",enabled:true,deleted:false)
Product.create(name:"Bagelers - Cinn / Brown Sugar",description:"magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae",price:"5.87",enabled:true,deleted:false)
Product.create(name:"Chick Peas - Dried",description:"sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed",price:"9.89",enabled:true,deleted:false)
Product.create(name:"Crab - Dungeness, Whole, live",description:"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum",price:"3.79",enabled:true,deleted:false)
Product.create(name:"Soup - Clam Chowder, Dry Mix",description:"semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam",price:"9.45",enabled:true,deleted:false)
Product.create(name:"Wine - Chablis 2003 Champs",description:"sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum",price:"8.66",enabled:true,deleted:false)
Product.create(name:"Carbonated Water - Orange",description:"habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante",price:"7.64",enabled:true,deleted:false)
Product.create(name:"Mushroom - Porcini Frozen",description:"dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum",price:"2.85",enabled:true,deleted:false)
Product.create(name:"Eggplant - Regular",description:"posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed",price:"8.34",enabled:true,deleted:false)
Product.create(name:"Liqueur - Melon",description:"augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus",price:"3.98",enabled:true,deleted:false)
Product.create(name:"Pepper - Red Bell",description:"eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare",price:"3.91",enabled:true,deleted:false)
Product.create(name:"Chivas Regal - 12 Year Old",description:"ut odio cras mi pede malesuada in imperdiet et commodo vulputate",price:"3.58",enabled:true,deleted:false)
Product.create(name:"Coffee - Ristretto Coffee Capsule",description:"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa",price:"2.08",enabled:true,deleted:false)
Product.create(name:"Ginsing - Fresh",description:"ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc",price:"5.79",enabled:true,deleted:false)
Product.create(name:"Wheat - Soft Kernal Of Wheat",description:"sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec",price:"3.86",enabled:true,deleted:false)
Product.create(name:"Bread - Dark Rye, Loaf",description:"eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus",price:"3.75",enabled:true,deleted:false)
Product.create(name:"Muffins - Assorted",description:"est et tempus semper est quam pharetra magna ac consequat metus",price:"7.40",enabled:true,deleted:false)
Product.create(name:"Beans - French",description:"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",price:"3.33",enabled:true,deleted:false)
Product.create(name:"Iced Tea - Lemon, 340ml",description:"ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices",price:"3.15",enabled:true,deleted:false)
Product.create(name:"Bouq All Italian - Primerba",description:"imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",price:"4.75",enabled:true,deleted:false)
Product.create(name:"Jello - Assorted",description:"erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a",price:"4.78",enabled:true,deleted:false)
Product.create(name:"Energy Drink - Redbull 355ml",description:"semper porta volutpat quam pede lobortis ligula sit amet eleifend",price:"5.72",enabled:true,deleted:false)
Product.create(name:"Tomatoes - Hot House",description:"laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis",price:"5.84",enabled:true,deleted:false)
Product.create(name:"Lamb Tenderloin Nz Fr",description:"facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget",price:"3.05",enabled:true,deleted:false)
Product.create(name:"Smoked Paprika",description:"auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl",price:"4.67",enabled:true,deleted:false)
Product.create(name:"Frangelico",description:"rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat",price:"8.18",enabled:true,deleted:false)
Product.create(name:"Crackers - Trio",description:"morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede",price:"2.58",enabled:true,deleted:false)
Product.create(name:"Corn - Cream, Canned",description:"vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor",price:"9.80",enabled:true,deleted:false)
Product.create(name:"Wine - Red, Metus Rose",description:"at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci",price:"9.24",enabled:true,deleted:false)
Product.create(name:"Foam Espresso Cup Plain White",description:"vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus",price:"6.25",enabled:true,deleted:false)
Product.create(name:"Cabbage - Red",description:"rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede",price:"2.53",enabled:true,deleted:false)
Product.create(name:"Pie Shells 10",description:"sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",price:"9.86",enabled:true,deleted:false)
Product.create(name:"Ezy Change Mophandle",description:"leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue",price:"2.00",enabled:true,deleted:false)
Product.create(name:"Apple - Royal Gala",description:"mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris",price:"9.62",enabled:true,deleted:false)
Product.create(name:"Beer - Camerons Cream Ale",description:"vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum",price:"8.03",enabled:true,deleted:false)
Product.create(name:"Eggplant - Baby",description:"in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus",price:"2.95",enabled:true,deleted:false)
Product.create(name:"Molasses - Fancy",description:"in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt",price:"6.01",enabled:true,deleted:false)
Product.create(name:"Bread - Petit Baguette",description:"integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis",price:"7.87",enabled:true,deleted:false)
Product.create(name:"Food Colouring - Pink",description:"eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",price:"2.05",enabled:true,deleted:false)
Product.create(name:"Oil - Olive, Extra Virgin",description:"diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",price:"6.46",enabled:true,deleted:false)
Product.create(name:"Wine - White, Ej",description:"rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean",price:"9.29",enabled:true,deleted:false)
Product.create(name:"Jameson - Irish Whiskey",description:"eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam",price:"5.57",enabled:true,deleted:false)
Product.create(name:"Longan",description:"luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit",price:"4.21",enabled:true,deleted:false)
Product.create(name:"Cheese - Mascarpone",description:"malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin",price:"2.18",enabled:true,deleted:false)
Product.create(name:"Veal - Shank, Pieces",description:"volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie",price:"2.98",enabled:true,deleted:false)
Product.create(name:"Pork - Liver",description:"platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat",price:"4.04",enabled:true,deleted:false)
Product.create(name:"Food Colouring - Green",description:"dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst",price:"3.82",enabled:true,deleted:false)
Product.create(name:"Spring Roll Veg Mini",description:"lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis",price:"8.34",enabled:true,deleted:false)
Product.create(name:"Duck - Legs",description:"platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",price:"3.13",enabled:true,deleted:false)
Product.create(name:"Apples - Spartan",description:"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer",price:"4.05",enabled:true,deleted:false)
Product.create(name:"Nescafe - Frothy French Vanilla",description:"aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus",price:"9.09",enabled:true,deleted:false)
Product.create(name:"Bread - Mini Hamburger Bun",description:"morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor",price:"4.30",enabled:true,deleted:false)
Product.create(name:"Pasta - Penne Primavera, Single",description:"donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis",price:"4.25",enabled:true,deleted:false)
Product.create(name:"Juice - Lagoon Mango",description:"tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim",price:"5.42",enabled:true,deleted:false)
Product.create(name:"Curry Powder Madras",description:"in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla",price:"5.19",enabled:true,deleted:false)
Product.create(name:"Tart Shells - Barquettes, Savory",description:"erat volutpat in congue etiam justo etiam pretium iaculis justo in hac",price:"8.91",enabled:true,deleted:false)
Product.create(name:"Wine - Red, Gallo, Merlot",description:"aliquet maecenas leo odio condimentum id luctus nec molestie sed",price:"3.92",enabled:true,deleted:false)
Product.create(name:"Nut - Pistachio, Shelled",description:"phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor",price:"9.69",enabled:true,deleted:false)
Product.create(name:"Lamb - Shoulder",description:"nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus",price:"9.45",enabled:true,deleted:false)
Product.create(name:"Bread - Bagels, Plain",description:"nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum",price:"3.31",enabled:true,deleted:false)
Product.create(name:"Jello - Assorted",description:"cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque",price:"3.83",enabled:true,deleted:false)
Product.create(name:"Chocolate Liqueur - Godet White",description:"metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies",price:"8.71",enabled:true,deleted:false)
Product.create(name:"Chicken - Whole",description:"felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",price:"3.41",enabled:true,deleted:false)
Product.create(name:"Mushroom - Shitake, Fresh",description:"eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",price:"7.61",enabled:true,deleted:false)
Product.create(name:"Wine - Guy Sage Touraine",description:"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum",price:"3.96",enabled:true,deleted:false)
Product.create(name:"Sea Bass - Fillets",description:"ut odio cras mi pede malesuada in imperdiet et commodo",price:"7.45",enabled:true,deleted:false)
Product.create(name:"Brandy - Orange, Mc Guiness",description:"pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti",price:"7.65",enabled:true,deleted:false)
Product.create(name:"Rice - Jasmine Sented",description:"ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim",price:"4.91",enabled:true,deleted:false)
Product.create(name:"Juice - Propel Sport",description:"in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus",price:"6.46",enabled:true,deleted:false)
Product.create(name:"Tuna - Salad Premix",description:"porta volutpat quam pede lobortis ligula sit amet eleifend pede libero",price:"3.10",enabled:true,deleted:false)
Product.create(name:"Sauce - Demi Glace",description:"tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",price:"5.61",enabled:true,deleted:false)
Product.create(name:"Beef - Tongue, Cooked",description:"nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a",price:"2.91",enabled:true,deleted:false)
Product.create(name:"Lobster - Baby, Boiled",description:"risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl",price:"6.07",enabled:true,deleted:false)
Product.create(name:"Sausage - Breakfast",description:"magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis",price:"3.87",enabled:true,deleted:false)
Product.create(name:"Beef - Tenderlion, Center Cut",description:"orci luctus et ultrices posuere cubilia curae donec pharetra magna",price:"5.86",enabled:true,deleted:false)
Product.create(name:"Flour - Corn, Fine",description:"morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non",price:"8.25",enabled:true,deleted:false)
Product.create(name:"Salt - Seasoned",description:"nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat",price:"7.83",enabled:true,deleted:false)
Product.create(name:"Wine - Sherry Dry Sack, William",description:"semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut",price:"8.10",enabled:true,deleted:false)
Product.create(name:"Pastry - Cheese Baked Scones",description:"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti",price:"8.27",enabled:true,deleted:false)
Product.create(name:"Pepper - Pablano",description:"velit eu est congue elementum in hac habitasse platea dictumst",price:"2.86",enabled:true,deleted:false)